[package]
name = "fuul-core"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish.workspace = true

[package.metadata.stellar]
cargo_inherit = true

[lib]
crate-type = ["lib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
stellar-contract-utils = { workspace = true }
stellar-access = { workspace = true, optional = true }

[features]
access-control = ["dep:stellar-access"]

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
